# Generated by Django 2.0.5 on 2018-07-01 19:15

from django.db import migrations, models
import django.db.models.deletion
import guests.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('invitation_closed', models.DateTimeField(blank=True, default=None, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone_number', models.TextField(blank=True, null=True)),
                ('is_attending', models.NullBooleanField(default=None)),
                ('is_child', models.BooleanField(default=False)),
                ('use_hotel', models.BooleanField(default=False)),
                ('invitation_id', models.CharField(db_index=True, default=guests.models._random_uuid, max_length=32, unique=True)),
                ('invitation_sent', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_invited', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('PL', 'polski'), ('ENG', 'english'), ('DE', 'deutsch')], default=('PL', 'polski'), max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Event')),
            ],
        ),
    ]
